### ISSUE TITLE
Error: Module version mismatch. Expected 43, got 14

### ISSUE THREAD

**Issue by kreja** [octalmage/pixelcolor#2]
I got the following error

```
[2688:0916/125018:ERROR:nw_shell.cc(336)] Error: Module version mismatch. Expected 43, got 14.
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/Users/kelly/codespace/test/nw-sample-apps/pixelcolor/node_modules/robotjs/index.js:1:80)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
[2688:0916/125018:INFO:CONSOLE(346)] "Uncaught Error: Module version mismatch. Expected 43, got 14.", source: module.js (346)
```

I searched this error and it seemed to be a version problem. What's the version of your nw?

**Comment by kumavis** [comment]
getting exact same error on a different repo, sorry not much help but

```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/piratechest ‹node-v0.12.7›  (master*) 
╰─$ node -v                                                                                                                                                                    130 ↵
v0.12.7
╭─kumavis@xyzs-MacBook-Pro  ~/dev/piratechest ‹node-v0.12.7›  (master*) 
╰─$ npm -v 
3.3.3
```

**Comment by octalmage** [comment]
Hey guys! 

This app uses nw.js, and with nw.js native modules need to be compiled with nw-gyp. You can read more about this here: 

https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

I'll get a packaged version up soon, but let me know if this helps!

**Comment by kumavis** [comment]
> https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

@octalmage this did it! thanks! :smile_cat:

**Comment by octalmage** [comment]
Fantastic! Glad I could help!
